<?php
    /***
     * Elevate API Core Drupal 7 Module
     * For use with the Ellucian Elevate API - http://www.ellucian.com/White-Papers/Ellucian-Elevate-Integration/
     *
     * Copyright (c) 2015-2016 Tyler Junior College.
     * See LICENSE file for MIT License information.
     ***/
     
     
    /**
     * Implementing hook_help
     **/
    
    function elevate_core_help($path, $arg) {
        if($path == "admin/help#elevate_core") {
            return t('Main Settings and Functionality to access Ellusian Elevate API.');
        }
    }
    
    